In [1]:
import pandas as pd

In [5]:
data= pd.read_csv('data.csv', index_col=0, sep=';')

In [6]:
data

,name,sequence,pI,net_charge_pH7,hydrophobicity,dipole_approx,rmsd_mean,rmsd_std,rmsf_mean,rmsf_std,...,gyrate-taf_std,energy_mean,energy_std,area_mean,area_std,hbond_protein_protein_mean,hbond_protein_protein_std,hbond_protein_water_mean,hbond_protein_water_std,melting point [°C]
0,h_pin1_r36a,KLPPGWEKRMSRSSGRVYYFNHITNASQWEAPSG,9.99,2.85,-1.07,82.62,211.0,24.0,78.00,36.00,...,12.00,592.335,24.166,30.800,825.000,17.831,1.912,95.367,4.566,56.7
1,h_pin1_r17g,KLPPGWEKRMSGSSGRVYYFNHITNASQWERPSG,9.99,2.85,-1.13,82.62,171.0,17.0,68.00,33.00,...,8.00,538.694,23.156,29.772,862.000,17.443,2.122,95.540,4.850,57.3
2,h_pin1_s32a,KLPPGWEKRMSRSSGRVYYFNHITNAAQWERPSG,10.42,3.85,-1.18,111.62,185.0,27.0,0.07,34.00,...,11.00,564.581,23.958,30.967,813.000,18.120,2.107,96.372,4.886,56.9
3,ms_n24,PLPGWEERQDVLGRTYYVNHESRTTQWKRPSPE,7.20,0.06,-1.59,0.30,267.0,52.0,0.11,79.00,...,15.00,488.743,23.500,31.562,1.045,20.880,2.506,106.070,5.611,45.4
4,h_pin1_n26d,KLPPGWEKRMSRSSGRVYYFDHITNASQWERPSG,9.98,2.85,-1.25,82.65,225.0,28.0,83.00,0.05,...,0.01,613.400,24.522,30.703,895.000,19.714,2.159,98.843,5.203,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,ms_n29,GLPSGWEERKDAKGRTYYVNHNNRTTTWTRPIMQ,9.98,2.85,-1.48,5.70,234.0,29.0,84.00,43.00,...,11.00,533.467,23.016,32.792,955.000,17.584,2.460,109.950,5.864,43.4
214,ms_n15,PLPPGWTEHKAPSGIPYYWNAELKKSTYQRPSFI,9.35,2.05,-0.89,24.54,186.0,32.0,88.00,43.00,...,0.01,493.558,22.734,32.166,864.000,14.959,1.854,90.182,4.620,47.1
215,cl_ww_lp2_2,PLPPGWEIRIGSGSGSIYYYNBGSKTTTWERPRL,9.55,1.96,-0.77,9.80,203.0,26.0,72.00,33.00,...,9.00,455.459,21.298,29.350,875.000,16.760,2.192,87.789,4.526,36.5
216,cl_ww_hs_ii,PLPPGWTIYIEANGRTYYYNSITKETTWERPRL,8.77,0.96,-0.90,4.81,175.0,26.0,0.07,0.03,...,0.01,571.235,23.583,30.251,833.000,19.218,2.254,91.374,4.870,78.0
217,cl_ww_bs2_4,PLPPGWEIRIGSGSGSISFYNHNTKTTTWERPRL,9.99,2.05,-0.82,10.25,222.0,29.0,79.00,33.00,...,0.01,520.259,22.573,29.858,935.000,17.366,2.278,91.491,4.931,37.0

In [ ]:
temp = pd.to_numeric(data["melting point [°C]"], errors="coerce")

invalid_rows = data[temp.isna()]

print(invalid_rows[["name", "melting point [°C]"]])

⚠️ Ungültige Werte in 'melting point [°C]':
            name melting point [°C]
7    h_pin1_p37a              <25.0
52   h_pin1_n26a              <10.0
83   h_pin1_y24a              <10.0
104  h_pin1_w11l                <10
109  h_pin1_w11a                <10
131  h_pin1_y24l              <10.0
172  h_pin1_p37i              <25.0
174  h_pin1_n26l              <10.0

In [8]:
data["melting point [°C]"] = data["melting point [°C]"].str.replace("<", "", regex=False).str.strip()

In [ ]:
temp = pd.to_numeric(data["melting point [°C]"], errors="coerce")

invalid_rows = data[temp.isna()]

print(invalid_rows[["name", "melting point [°C]"]])

⚠️ Ungültige Werte in 'melting point [°C]':
Empty DataFrame
Columns: [name, melting point [°C]]
Index: []

In [10]:
data.to_csv('new_data.csv')

In [16]:
new = pd.read_csv('new_data.csv', index_col=0)

In [17]:
new

,name,sequence,pI,net_charge_pH7,hydrophobicity,dipole_approx,rmsd_mean,rmsd_std,rmsf_mean,rmsf_std,...,gyrate-taf_std,energy_mean,energy_std,area_mean,area_std,hbond_protein_protein_mean,hbond_protein_protein_std,hbond_protein_water_mean,hbond_protein_water_std,melting point [°C]
0,h_pin1_r36a,KLPPGWEKRMSRSSGRVYYFNHITNASQWEAPSG,9.99,2.85,-1.07,82.62,211.0,24.0,78.00,36.00,...,12.00,592.335,24.166,30.800,825.000,17.831,1.912,95.367,4.566,56.7
1,h_pin1_r17g,KLPPGWEKRMSGSSGRVYYFNHITNASQWERPSG,9.99,2.85,-1.13,82.62,171.0,17.0,68.00,33.00,...,8.00,538.694,23.156,29.772,862.000,17.443,2.122,95.540,4.850,57.3
2,h_pin1_s32a,KLPPGWEKRMSRSSGRVYYFNHITNAAQWERPSG,10.42,3.85,-1.18,111.62,185.0,27.0,0.07,34.00,...,11.00,564.581,23.958,30.967,813.000,18.120,2.107,96.372,4.886,56.9
3,ms_n24,PLPGWEERQDVLGRTYYVNHESRTTQWKRPSPE,7.20,0.06,-1.59,0.30,267.0,52.0,0.11,79.00,...,15.00,488.743,23.500,31.562,1.045,20.880,2.506,106.070,5.611,45.4
4,h_pin1_n26d,KLPPGWEKRMSRSSGRVYYFDHITNASQWERPSG,9.98,2.85,-1.25,82.65,225.0,28.0,83.00,0.05,...,0.01,613.400,24.522,30.703,895.000,19.714,2.159,98.843,5.203,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,ms_n29,GLPSGWEERKDAKGRTYYVNHNNRTTTWTRPIMQ,9.98,2.85,-1.48,5.70,234.0,29.0,84.00,43.00,...,11.00,533.467,23.016,32.792,955.000,17.584,2.460,109.950,5.864,43.4
214,ms_n15,PLPPGWTEHKAPSGIPYYWNAELKKSTYQRPSFI,9.35,2.05,-0.89,24.54,186.0,32.0,88.00,43.00,...,0.01,493.558,22.734,32.166,864.000,14.959,1.854,90.182,4.620,47.1
215,cl_ww_lp2_2,PLPPGWEIRIGSGSGSIYYYNBGSKTTTWERPRL,9.55,1.96,-0.77,9.80,203.0,26.0,72.00,33.00,...,9.00,455.459,21.298,29.350,875.000,16.760,2.192,87.789,4.526,36.5
216,cl_ww_hs_ii,PLPPGWTIYIEANGRTYYYNSITKETTWERPRL,8.77,0.96,-0.90,4.81,175.0,26.0,0.07,0.03,...,0.01,571.235,23.583,30.251,833.000,19.218,2.254,91.374,4.870,78.0
217,cl_ww_bs2_4,PLPPGWEIRIGSGSGSISFYNHNTKTTTWERPRL,9.99,2.05,-0.82,10.25,222.0,29.0,79.00,33.00,...,0.01,520.259,22.573,29.858,935.000,17.366,2.278,91.491,4.931,37.0